### ISSUE TITLE
Can't dismiss tooltip after downloading translation model

### ISSUE THREAD

**Issue by aguynamedryan** [audapolis/audapolis#151]
When given the chance to download a translation model, I opted to download two at the same time.  When the first one completed, I found myself stuck in a loop with the tool tip.  Please see attached GIF.

![bugaboo](https://user-images.githubusercontent.com/117722/145858572-241b2059-2cb3-4154-9024-5b51a2efae9b.gif)

**Comment by pajowu** [comment]
Oh, that's not good. Thanks for reporting this, I will try to reproduce and fix that shortly
