### ISSUE TITLE
Export text of transcript

### ISSUE THREAD

**Issue by ebdavison** [audapolis/audapolis#164]
It would be a great addition to this very useful program it it could export the text of the transcript as well as the bits/mp3/mp4 selections.

**Comment by schnip** [comment]
I've also been trying to figure out how to extract the text of the transcription, The best way I have found is to select as much text as I can on the screen, and then drag off screen on to an awaiting text editor.

**Comment by pajowu** [comment]
Yes, we should definitely do this, I planned to do this already but never got to it. There was some preliminary support for it before we implemented copy&paste. I think most of the needed functions are still there. It should be easy to add a button similar to the "Export"-button shown when you select a part of the document. We are currently switching to a proper component library (see #156), but after that I will look into this

**Comment by ebdavison** [comment]
Thanks for the update; I will keep an eye on this ticket.  Also, I will try the workaround mentioned by schnip.

**Comment by ebdavison** [comment]
As a note, the workaround is, well, workable but it is a bit clunky.  Looking forward the the actual Export function.

**Comment by pajowu** [comment]
Ah, I forgot to update you about this issue. I added a button for that in #200, which you can test in v0.2-beta1: https://github.com/audapolis/audapolis/releases/tag/v22.1.7-2022
