### ISSUE TITLE
Failed to export

### ISSUE THREAD

**Issue by xPMo** [audapolis/audapolis#165]
I'm not sure what help I can provide, I've been unable to export any audio from Audapolis, I'm primarily on Linux (appimage), but it fails on Windows as well. I'm unfamiliar with web debugging, but I found the devtools and got the error here:

```
Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:562:9)
    at FFmpegCommand.spawn (/tmp/.mount_audapoyYVf1Z/resources/app.asar/node_modules/@tedconf/fessonia/lib/ffmpeg_command.js:201:21)
    at combineParts (file:///tmp/.mount_audapoyYVf1Z/resources/app.asar/build/renderer/assets/index.56f60b7b.js:785:7)
    at exportContent (file:///tmp/.mount_audapoyYVf1Z/resources/app.asar/build/renderer/assets/index.56f60b7b.js:839:9)
    at async file:///tmp/.mount_audapoyYVf1Z/resources/app.asar/build/renderer/assets/index.56f60b7b.js:1014:3
```

Windows ends up giving `ENOENT` instead. Saving an audapolis project works perfectly fine, though.

Let me know what steps would be helpful to narrowing it down for you.

Thanks for your work, I look forward to using this in the (hopefully-near) future!

> **Tangent**: [Quick and dirty script I'm using as a workaround](https://gitlab.com/xPMo/snippets/-/blob/master/shell/audapolis-export.zsh)

**Comment by pajowu** [comment]
Oh, interesting. Thanks for filing an issue. In the JS console it should show you an ffmpeg-command right before this error. Can you try if the ffmpeg-binary that is used there in executable on your machine? And if the command in general seems to be alright?

**Comment by xPMo** [comment]
Ah, found it, had to enable verbose output:
```bash
/tmp/.mount_audapoKmLYA1/resources/app.asar/node_modules/ffmpeg-static/ffmpeg '-y' ...
```
Should be:
```bash
/tmp/.mount_audapoKmLYA1/resources/app.asar.unpacked/node_modules/ffmpeg-static/ffmpeg '-y' ...
```
So the `ENOTDIR` is because `.../app.asar/` does not exist.

**Comment by pajowu** [comment]
Ah! I found the issue. We did not disable asar-packing for our releases. #173 shoud fix this.

Good point regarding the `too many arguments`. I hope that this will not be a problem right now, but I opened #174 to investigate this further
