### ISSUE TITLE
Improvement code in the transcription core function

### ISSUE THREAD

**Issue by johnidm** [audapolis/audapolis#167]
It is possible to loop audio by steps using slice syntax in Pydub. See https://github.com/jiaaro/pydub/issues/221

An interesting code improvement is to change the code -  https://github.com/audapolis/audapolis/blob/main/server/app/transcribe.py#L56
```
finished = False
while not finished:
    block_start = task.processed
    block_end = task.processed + VOSK_BLOCK_SIZE
    data = audio[block_start * 1000 : block_end * 1000]
    if block_end > task.total:
        block_end = task.total
        finished = True
    rec.AcceptWaveform(data.get_array_of_samples().tobytes())
    task.processed = block_end
``` 
To
```
for chunk in audio[::VOSK_BLOCK_SIZE * 1000]:
    data = chunk.get_array_of_samples().tobytes()
    rec.AcceptWaveform(data)
```
Thanks for your work.

**Comment by pajowu** [comment]
Oh, nice one.

**Comment by pajowu** [comment]
I checked again and after merging #132 it no longer works for our usecase. We need to transcribe only part of a file where the length of our audio is not a whole multiple of our block length (https://github.com/audapolis/audapolis/commit/0d9a67f5dec71ed6806444bb2170c735d3154288#diff-7c76cea116f2b4de145d31fa93ca5dd8c760bed36c6b2f7140c2de0a78fbf861R44). The slice syntax always produces chunks of the step size:

```python
>>> from pydub import AudioSegment
>>> audio = AudioSegment.from_wav("file.wav")
>>> first_chunk = next(audio[:100:1000])
>>> len(first_chunk)
1000
```

**Comment by pajowu** [comment]
However I want to thank you a lot for bringing this up and should you figure out a way to do this properly with the new requirements, we would be really happy if you would open up a pull request for it
