### ISSUE TITLE
Cannot navigate using right arrow

### ISSUE THREAD

**Issue by jgarplind** [audapolis/audapolis#217]
Same baseline as previous issue:

> Hope you don't mind me leaving feedback here. If so, feel free to close.
I recorded a 210MB/35 minute .mkv-video and tried to do some things. The resulting .audapolis file is of similar size.

Navigating with left arrow takes me to the previous word. Using the up arrow scrolls the document upwards. Using the down arrow scrolls the document downwards.

Using the right arrow key, however, has no apparent effect. No errors are thrown either. I would have expected to be navigated to the next word, opposite of left arrow key behavior.

In a smaller file, right arrow key still doesn't work, and up/down keys also have no effect since there is no scrolling to be done.

**Comment by anuejn** [comment]
Thanks for reporting, i will investigate :)
