### ISSUE TITLE
getting error after install and run

### ISSUE THREAD

**Issue by Arunk28** [audapolis/audapolis#219]
after clone the repo 
install the  npm i and npm start 
get error 

![image](https://user-images.githubusercontent.com/7352047/148951029-d10ce198-759e-47a5-85a0-2e73c3b67c9b.png)

**Comment by pajowu** [comment]
Hey, thank's for raising this issue. Do you have [poetry](https://python-poetry.org/) installed? This is needed for the backend-components of audapolis

**Comment by Arunk28** [comment]
nope will install and try .,

**Comment by anuejn** [comment]
the docs should cover this after #247 lands

**Comment by pajowu** [comment]
I think this is closed with #247. If not, please reopen this issue
