### ISSUE TITLE
Multiple audio files

### ISSUE THREAD

**Issue by kishan2k** [audapolis/audapolis#242]
Allow importing, transcribing and editing of two or more audio files, and maybe even exporting them individually for post editing.

**Comment by pajowu** [comment]
Just to clarify: Do you want to process multiple files as one longer file or do you want to edit them in parallel.

The second thing actually already works, but is a bit hidden. You can use "Window->New Window" or the shortcut `CTRL+N` / `⌘+N` to open a new audapolis window, in which you can transcribe/open/etc a new file in parallel. You can even copy-paste between them

**Comment by pajowu** [comment]
Thank you a lot for this suggestion.

As noted in my previous comment, you can already edit multiple files at once by creating a new window with <kbd>Ctrl</kbd>+<kbd>N</kbd>. We also have an issue now for importing multiple files at once: #260.

I currently can't really imagine a use case where you would import multiple files "as one", i.e. select multiple files but end up with one audapolis file of those concatenated. If you have an example of how that could be useful, please comment it here and re-open the issue.
