### ISSUE TITLE
Numpy library has wrong filename

### ISSUE THREAD

**Issue by pajowu** [audapolis/audapolis#258]
Numpy reports an error because it cannot find `libopenblasp-r0-2d23e62b.3.17.so`. Our bundle includes this file, but under the wrong name: `libopenblasp-r0-2d23e62b/3/17.so` (yes, those are multiple subdirectories). This leads to the server crashing on start

**Comment by anuejn** [comment]
on which platform is that?

**Comment by pajowu** [comment]
Linux

**Comment by anuejn** [comment]
fixed in #277
