### ISSUE TITLE
don't select word when right-clicking on it

### ISSUE THREAD

**Issue by pajowu** [audapolis/audapolis#312]

**Comment by anuejn** [comment]
I think this is sensible behaviour?
This way I just right click on a word enter the correct word and press enter.

**Comment by pajowu** [comment]
sorry, the issue title was a bit unclear: We should select the text in the input field. We should not select the word (as in `state.editor.selection`)

**Comment by pajowu** [comment]
This is what happens on my machine:

https://user-images.githubusercontent.com/6545097/154984282-62fc0e6b-fbb3-40a7-a519-5061907c7a94.mov

You can see that some form of selection happend outside of/behind the input field

**Comment by anuejn** [comment]
ah i see. that makes a lot of sense
