### ISSUE TITLE
Selection of the first word is broken?

### ISSUE THREAD

**Issue by anuejn** [audapolis/audapolis#36]
See gif
![Peek 2021-09-20 12-39](https://user-images.githubusercontent.com/8377902/133995997-73c19f89-b44b-4fe2-b8fa-e0c22846118e.gif)

**Comment by anuejn** [comment]
This seems to be not a selection issue but something else that causes the start of that word to be somewhere absurd

**Comment by pajowu** [comment]
Maybe fixed by #53?

**Comment by anuejn** [comment]
sounds like it

**Comment by anuejn** [comment]
probably fixed
