### ISSUE TITLE
Can't cancel download of transcription model

### ISSUE THREAD

**Issue by thelegend09** [audapolis/audapolis#380]
I clicked on a model by accident, but I couldn't stop the download.

I was expecting to see an "x" on top of the circle that indicates the download progress, which I could click to stop the download.

**Comment by pajowu** [comment]
This should be possible, but there was a slight bug that made the x not appear sometimes. This is fixed in the current master, but I think not in the latest release

**Comment by pajowu** [comment]
I just released a new pre-release for the next version of audapolis, which contains the fix for that. Please try this release and reopen the bug if it still doesn't work as expected: https://github.com/audapolis/audapolis/releases/tag/v0.2.2-pre2
