### ISSUE TITLE
missing application icon

### ISSUE THREAD

**Issue by mash-graz** [audapolis/audapolis#397]
There is another minor issue to report:

The application doesn't show any icon in the window managers (in may case: `cinnamon`) application start menu and task bar on debian linux. it's hindering a more comfortable use resp. switching between tasks,

**Comment by pajowu** [comment]
Interesting. Those _should_ be autogenerated by electron-builder. I'll take a look once I have a debian installation running

**Comment by pajowu** [comment]
Apparently this is a bug in electron-builder: https://github.com/electron-userland/electron-builder/issues/5294. #399 should be a workaround
