### ISSUE TITLE
Add cli UI to simplify bulk imports

### ISSUE THREAD

**Issue by RichardBronosky** [audapolis/audapolis#407]
I have 80 audio files to import. I can use `vosk-transcribe` on the CLI, but I cannot import the resultant JSON. Please advise.

**Comment by RichardBronosky** [comment]
I have discovered https://github.com/audapolis/audapolis/blob/main/server/scripts/transcribe.py but I've not yet figured out how to correctly pass the `PUNCTUATION_MODEL` and `transcription_model_id`. I'm trying to use the 1.8GB vosk-model-en-us-0.22.zip for transcription. Any help would be appreciated.

```plain
$ python3 scripts/transcribe.py --server $server --token $token --diarize $file $model

Uploading /home/bruno/Documents/VP_10/1/RECORDER/VP100008.MP3
{'detail': [{'loc': ['query', 'lang'],
             'msg': 'field required',
             'type': 'value_error.missing'},
            {'loc': ['query', 'model'],
             'msg': 'field required',
             'type': 'value_error.missing'}]}
Traceback (most recent call last):
  File "/home/bruno/src/audapolis/server/scripts/transcribe.py", line 40, in <module>
    f"{args.server}/tasks/{upload_req.json()['uuid']}/", headers=headers
KeyError: 'uuid'
```

**Comment by RichardBronosky** [comment]
I currently looking into https://github.com/audapolis/audapolis/blob/main/server/app/models.yml#L5-L10 to find valid values. Trying `punctuator2-subtitle2go` gets an encouraging response. Not yet sure if it generates valuable results.

**Comment by pajowu** [comment]
I'm not sure if the transcribe-script is up to date with the current api, this was a script I used while developing some features, not really meant for production usage.

**Comment by pajowu** [comment]
In the long run, I would prefer to have a proper UI for this (see #260) than to have a CLI tool for this, but for now updating transcribe.py might be better

**Comment by pajowu** [comment]
I updated the script for the newest api / file format, in the branch `pajowu/transcribe_script` (see #408)

**Comment by pajowu** [comment]
The command now is
```bash
poetry run python scripts/transcribe.py --server [SERVER_URL] --token [TOKEN] --punctuation-model punctuator2-subtitle2go --diarize --transcription-model small --language German [FILENAME]
```
