### ISSUE TITLE
0.2.2-pre3 - Stuck at 'Starting App...'

### ISSUE THREAD

**Issue by GOvEy1nw** [audapolis/audapolis#426]
Checked debug log and get this error:

{"date":"2023-03-23T09:17:54.366Z","source":"RendererProcess","level":"Log","args":["\"FileNotFoundError: [WinError 3] The system cannot find the path specified: 

`'C:\\\\\\\\Users\\\\\\\\USERNAME\\\\\\\\AppData\\\\\\\\Local\\\\\\\\Programs\\\\\\\\audapolis\\\\\\\\resources\\\\\\\\server\\\\\\\\libs'\\r\""]}`

checking that location, I have a 'lib' folder but not a 'libs' folder

**Comment by pajowu** [comment]
This should be fixed with https://github.com/audapolis/audapolis/pull/427, once this is merged, I will publish a new pre-release for you to try

**Comment by pajowu** [comment]
Please try this version: https://github.com/audapolis/audapolis/releases/tag/v0.2.2-pre4
