### ISSUE TITLE
I'm looking for the Japanese version now.

### ISSUE THREAD

**Issue by JhoushuTomato** [audapolis/audapolis#431]
Is there no Japanese version in this version?
You can also download VOSK, a voice recognition tool that supports Japanese.
I did, but can't I use it?
Sorry for the machine translation.

**Comment by anuejn** [comment]
Audapolis does not currently have a translated User-Interface (it is all in English).
Is this what you are looking for?

**Comment by JhoushuTomato** [comment]
>Audapolis does not currently have a translated user interface (all in English).
Thank you for your reply.
The user interface does not have a Japanese version,
Then, can voice recognition support Japanese?
Can it be recognized if Vosk for Japanese is introduced?

**Comment by pajowu** [comment]
The voice recognition supports japanese. If it doesn't work, please open a new bug report

**Comment by JhoushuTomato** [comment]
> Voice recognition supports Japanese.
Is it possible to internationalize the UI with something like POEDIT?
Is there some sort of user manual that gives detailed instructions on how to operate it?

Apparently I don't understand your software. excuse me.
________________________________
差出人: pajowu ***@***.***>
送信日時: 2023年5月3日 23:20
宛先: audapolis/audapolis ***@***.***>
CC: Jhoushu-Tomato ***@***.***>; State change ***@***.***>
件名: Re: [audapolis/audapolis] I'm looking for the Japanese version now. (Issue #431)


The voice recognition supports japanese. If it doesn't work, please open a new bug report
